=== GuioSanada/DAW/JSON/Relacion1/esquemaAlumnos.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Alumnos",
    "description": "Schema de alumnos",
    "type": "array",
    "items": {
      "description": "listado de alumnos con sus asignaturas",
      "type": "object",
      "properties": {
        "nombre": {
          "type": "string",
          "description": "El nombre del alumno/a"
        },
        "dni": {
          "type": [
            "number",
            "string"
          ],
          "description": "El dni del alumno/a con o sin letra"
        },
          "direccion": {
          "type": "string",
          "description": "Direccion del alumno/a"
        },
        "telefono":{
            "patternProperties": {
                "[0-9]{9}":{
                    "description": "Numero de telefono de los alumnos/as"
                }
            },
            "type": "string"
        },
        "asignaturas": {
          "type": "object",
          "description": "cada una de las asignaturas de los alumnos/as",
          "patternProperties": {
            "[A-Z]{2}": {
              "description": "cada una de las asignaturas",
              "type": "object",
              "required": [
                "nombre"
              ],
              "properties": {
                "nombre": {
                  "type": "string"
                },
                "caliÔ¨Åcacion": {
                  "type": "integer"
                }
              }
            }
          }
        }
      },
      "required": [
        "nombre",
        "dni",
        "asignaturas"
      ]
    },
    "uniqueItems": true
  }

=== GuioSanada/DAW/JSON/Relacion1/ejercicio2.json
[
    {
        "nombre" : "Antonio",
        "dni" : "11111111A",
        "direccion" : "Camino a VillaFlora",
        "telefono" : "650802790",
        "asignaturas" : {
            "LC" : {
                "nombre" : "LC",
                "calificacion" : 10
            },
            "DES" : {
                "nombre" : "DES",
                "calificacion" : 10
            },
            "DEC" : {
                "nombre" : "DEC",
                "calificacion" : 10
            }
            
        }
    },

    {
        "nombre" : "Jorge",
        "dni" : "11111112A",
        "direccion" : "Torre del Mar",
        "telefono" : "611111111",
        "asignaturas" : {
            "LC" : {
                "nombre" : "LC",
                "calificacion" : 10
            },
            "DES" : {
                "nombre" : "DES",
                "calificacion" : 10
            },
            "EIE" : {
                "nombre" : "EIE",
                "calificacion" : 10
            }
            
        }
    },

    {
        "nombre" : "La Luiza",
        "dni" : "11111113A",
        "direccion" : "cordobah",
        "telefono" : "622222222",
        "asignaturas" : {
            "LC" : {
                "nombre" : "LC",
                "calificacion" : 9
            },
            "DES" : {
                "nombre" : "DES",
                "calificacion" : 10
            },
            "DEC" : {
                "nombre" : "DEC",
                "calificacion" : 8
            }
            
        }
    },

    {
        "nombre" : "Ez√∫",
        "dni" : "11111114A",
        "direccion" : "Marbella",
        "telefono" : "633333333",
        "asignaturas" : {
            "DI" : {
                "nombre" : "DI",
                "calificacion" : 10
            },
            "DES" : {
                "nombre" : "DES",
                "calificacion" : 10
            },
            "DEC" : {
                "nombre" : "DEC",
                "calificacion" : 3
            }
            
        }
    }
]
